
export const ChatList = [
    {
        name:'Jack',
        status:'Available',
        dp:'https://png.pngtree.com/png-clipart/20230824/original/pngtree-boy-avatar-in-round-web-button-isolated-on-white-picture-image_8377276.png'
    },
    {
        name:'Harry',
        status:'Available',
        dp:'https://static.vecteezy.com/system/resources/previews/019/896/008/original/male-user-avatar-icon-in-flat-design-style-person-signs-illustration-png.png'
    },
    {
        name:'Stella',
        status:'Available',
        dp:'https://cdn.icon-icons.com/icons2/2643/PNG/512/female_woman_avatar_people_person_white_tone_icon_159370.png'
    },
    {
        name:'Ezabela',
        status:'Offline',
        dp:'https://www.pikpng.com/pngl/b/279-2797047_user-avatar-icon-portable-network-graphics-clipart.png'
    },
    {
        name:'Tony',
        status:'Available',
        dp:'https://www.pngall.com/wp-content/uploads/12/Avatar-Profile-Vector-PNG-Cutout.png'
    },
    {
        name:'Charles',
        status:'Available',
        dp:'https://icons.veryicon.com/png/o/miscellaneous/user-avatar/user-avatar-male-5.png'
    },
    {
        name:'Xavier',
        status:'Available',
        dp:'https://ps.w.org/user-avatar-reloaded/assets/icon-256x256.png?rev=2540745'
    },

]